---

- name: install centos configurator
  copy:
    src: centos_bootstrap
    dest: /etc/rc.d/rc.local
    owner: root
    group: root
    mode: 0755

- name: we have security groups so iptables is not needed
  systemd: 
    name: firewalld
    enabled: no
    state: stopped
